spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?serverTimezone=UTC&character=utf-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
user:
  address:
    max-count: 20